openapi: "3.0.1"
info:
  title: "PeTaL API"
  version: "6"
servers:
- url: "https://unbqm6hov8.execute-api.us-east-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "v1"
paths:
  /getarticles:
    get:
      tags:
      - "API methods"
      summary: "Finds articles by label"
      description: "Find articles with the level2 and level3 labels supplied."
      parameters:
      - name: "level3"
        in: "query"
        description: "The third level label to retreive articles for."
        schema:
          type: "string"
      - name: "level2"
        in: "query"
        description: "The second level label to retreive articles for."
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /getallarticles:
    get:
      tags:
      - "API methods"
      summary: "Get all articles"
      responses:
        "200":
          description: "successful operation"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
